### ISSUE TITLE
Replace let with var

### ISSUE THREAD

**Issue by Unsfer** [davidtheclark/postcss-resolve-nested-selector#19]
Can you please replace `let` with `var` in `for (let letter of string)`?

**Comment by romainmenke** [comment]
Hi @Unsfer 

Can you say why this would be needed?

**Comment by Unsfer** [comment]
Hi.
I have very old environment, which I cannot update, unfortunately.
When building it throws now:
`Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`
Not a serious issue, downgraded version of postcss-resolve-nested-selector  for now

**Comment by romainmenke** [comment]
Which node version?

I don't mind making such changes as long as it doesn't bloat the codebase or introduce extra dependencies. Changing `let` to `var` seems fine to me. But I want to test that it then actually works and doesn't just throw again a few lines later :)

**Comment by Unsfer** [comment]
node v4.6.1

**Comment by romainmenke** [comment]
I have no idea how to test such an extremely old node version.
Nothing supports that.

So this was a best effort patch.
I've released `0.1.5` where I use `var` instead of `let`.
Hopefully that works for you 🤞

**Comment by Unsfer** [comment]
It's working with the latest version. I'll test it for some time and make a response. 
Thanks a ton!

**Comment by romainmenke** [comment]
Awesome!

Closing for now, If you still have a problem, please file a new issue and then we will take a look :)

Thank you again for reporting.
