### ISSUE TITLE
Release new version with support postcss v6

### ISSUE THREAD

**Issue by alexander-akait** [davidtheclark/postcss-resolve-nested-selector#3]

**Comment by davidtheclark** [comment]
I'll do that this morning. Also, added you and other stylelint collaborators to this repo.

**Comment by davidtheclark** [comment]
@evilebottnawi Just pushed a commit that uses PostCSS 6 for tests. All the tests pass, and PostCSS was never included as a dependency of the project ... so I don't think we need a new release. Am I missing something?

**Comment by alexander-akait** [comment]
@davidtheclark oh, it seemed to me what `postcss` in `dep`, but it is good to confirm all tests passed on postcss v6
